apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: action-test
on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: no-op
        uses: docker://alpine:3.21
        run: echo ""

      - name: configure-eks
        cloudbees-io/configure-eks-credentials@v1
        with:
          name: ${{ vars.staging_east_cluster_name }}

