apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: action-test
on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: no-op
        uses: docker://alpine:3.21
        run: echo ""

      - name: configure-eks
        uses: cloudbees-io/configure-eks-credentials@19edc03f8648cbf2215b5fc49a991a4bea60c0b2
        with:
          name: 'nonexistent'

