apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: action-test
on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: no-op
        uses: docker://alpine:3.21
        run: echo ""
