apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: action-test
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600"
