apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-env-1

on: 
  workflow_call:
    secrets:
      top_secret:
        required: true

jobs:
  inner-1:
    steps:
      - name: test secret value
        uses: docker://alpine:3.21
        run: |
          [ "${{ secrets.top_secret }}" = "secretFromEnv" ]