apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-env-root

on:
  workflow_dispatch:

jobs: 
  deploy:
    uses: p-gombola/demo-app/.cloudbees/workflows/call-rw-env-1.yaml@main
    environment: secret-env
    secrets:
      top_secret: secrets.secretFromEnv