apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-env-1

on: 
  workflow_call:
    secrets:
      top_secret:
        required: true

jobs:

  call-rw-2:
    uses: p-gombola/demo-app/.cloudbees/workflows/call-rw-env-2.yaml@main
    secrets:
      top_secret_2: ${{ secrets.top_secret }}