apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-env-root

on:
  workflow_dispatch:

jobs: 
  deploy:
    environment: secret-env
    uses: p-gombola/shared/.cloudbees/workflows/call-rw-env-1.yaml@main
    secrets:
      top_secret: ${{ secrets.fromEnv }}