apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-var-root

on:
  workflow_dispatch:

jobs: 
  deploy:
    uses: p-gombola/demo-app/.cloudbees/workflows/call-rw-var-1.yaml@main
    with:
      var_1: 999