apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-env-1

on: 
  workflow_call:
    secrets:
      top_secret:
        required: true

jobs:
  inner-1:
    steps:
      - name: test secret value
        uses: docker://alpine:3.21
        run: |
          [ "${{ secrets.top_secret }}" = "secretFromEnv" ]

  call-rw-2:
    uses: p-gombola/shared/.cloudbees/workflows/call-rw-env-2.yaml@main
    secrets:
      top_secret_2: ${{ secrets.top_secret }}