apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call-rw-var-2

on:
  workflow_call:
    inputs:
      var_2:
        type: number
        required: true

jobs:
  inner-2:
    steps:
      - name: test secret value
        uses: docker://alpine:3.21
        run: |
          [ ${{ inputs.var_2 }} = 999 ]