apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: codeship test

on:
  workflow_dispatch:

jobs:
  run-tests:
    steps:
      - name: Run test pipeline
        uses: docker://cloudbees/basic-platform:pr-image-rspec
        run: |
            . /etc/cloudbees.sh
            if [ -f .ruby-version ]; then rvm use $(cat .ruby-version) --install; fi
            EXPORT GEM_HOME="$HOME/.gem"
            if [ -f .bundler-version ]; then gem install bundler -v $(cat .bundler-version); else gem install bundler; fi
            apt-get update
            apt-get install -y libxml2-dev shared-mime-info libvips42
            if [ -f .node-version ]; then nvm install $(cat .node-version); else nvm install 16.18.0; fi