apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: codeship test

on:
  workflow_dispatch:

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16.8-alpine3.21
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7.4.2-alpine3.21
    steps:
      - name: Run test pipeline
        uses: docker://cloudbees/basic-platform:0.0.271-rspec
        run: |
            . /etc/cloudbees.sh
            export GEM_HOME=$(pwd)

            if [ -f .ruby-version ]; then rvm use $(cat .ruby-version) --install; fi
            if [ -f .bundler-version ]; then gem install bundler -v $(cat .bundler-version); else gem install bundler; fi
            bundle install
            if [ -f .node-version ]; then nvm install $(cat .node-version); else nvm install 16.18.0; fi
            corepack enable
            corepack prepare yarn@stable --activate
            yarn set version stable
            yarn install
            export RAILS_ENV=test

            until pg_isready -h 127.0.0.1 -q; do
              echo "Waiting for database connection..."
              sleep 2
            done

            until redis-cli -h 127.0.0.1; do
              echo "Waiting for redis connection..."
              sleep 2
            done