apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: codeship test

on:
  workflow_dispatch:

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16.8-alpine3.21
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - name: Run test pipeline
        uses: docker://cloudbees/basic-platform:pr-image-rspec
        run: |
            until pg_isready; do
              echo "Waiting for database connection..."
              sleep 2
            done