apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: codeship test

on:
  workflow_dispatch:

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16.8-alpine3.21
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7.4.2-alpine3.21
    steps:
      - name: Run test pipeline
        uses: docker://cloudbees/basic-platform:pr-image-rspec
        run: |
            until pg_isready -h 127.0.0.1 -q; do
              echo "Waiting for database connection..."
              sleep 2
            done

            until redis-cli -h 127.0.0.1; do
              echo "Waiting for redis connection..."
              sleep 2
            done