apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: max-reusable

on:
  workflow_dispatch:

jobs:
  rw-dynamic-env:
    uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-dynamic-environment.yaml
    secrets: inherit
    vars: inherit
    with:
      environment: pg-prod

  rw-mapped-secrets:
    uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-secrets-mapping.yaml
    secrets:
      super_secret: ${{ secrets.secret1 }}
      
  rw-dynamic-env-mapped-secrets:
    uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-dynamic-env-secrets-mapping.yaml
    secrets:
      env_only_secret_prop: "override env secret from mapping"
      secret1: ${{ secrets.secret1 }}
    vars: inherit
    with:
      environment: pg-prod

  rw-mapped-undeclared-secret:
    uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-undeclared-secret.yaml
    secrets:
      mysecret: ${{ secrets.secret1 }}
  
  rw-using-global-secrets:
    uses: p-gombola/dmeo-app/.cloudbees/workflows/reusable-using-global-secrets.yaml
    secrets: inherit
    vars: inherit