apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: max-reusable`

on:
  workflow_dispatch:

jobs:
  reusable-workflow-with-dynamic-environment:
    uses: ./workflows/reusable-with-dynamic-environment.yaml
    secrets: inherit
    vars: inherit
    with:
      environment: PROD