apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Memory Limit

on:
  workflow_dispatch: {}

jobs:
  exceed-memory-limit:
    steps:
      - id: checkout
        name: Get source code
        uses: cloudbees-io/checkout@v1

      - name: golang exceed memory limit
        if: ${{ true }}
        uses: docker://golang:1.24-alpine3.21
        run: |
          go run main.go
      
      - name: shell exceed memory limit
        if: ${{ false }}
        uses: docker://alpine:3.21
        run: |
          echo "Free memory: $(expr $(cat /proc/meminfo | awk '/MemFree/{printf "%d\n", $2 * 0.9;}') / 1024 / 1024)GiB"
          echo
          echo Generating 1GiB file ...
          cat /dev/urandom | tr -dc _A-Z-a-z-0-9 | head -c $(expr 1024 \* 1024 \* 1024) > file
          VAR=
          SIZE=0
          for IDX in $(seq 1 15); do
            SIZE=$(expr $SIZE + 1)
            echo Loading generated file into memory ${SIZE}x ...
            VAR="$VAR$(cat file))"
          done