apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-with-nested-environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  use-environment:
    environment: ${{ inputs.environment }}
    steps:
      - uses: docker://alpine:3.21
        run: |
          set -x
          [ "$ENVSECRET" = 'use me only for prod' ]
        env:
          ENVSECRET: ${{ secrets.env_only_secret_prop }}

  call-rw-2:
    uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-nested-environment-2.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}