apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-with-secrets-mapping

on:
  workflow_call:
    secrets:
      super_secret:
        required: true

jobs:
  use-mapped-secret:
    steps:
      - uses: docker://alpine:3.21
        run: |
          set -x
          [ "$ENVSECRET" = 'secretValue1' ]
        env:
          ENVSECRET: ${{ secrets.super_secret }}