apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-with-dynamic-environment-mapped-secrets

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      env_only_secret_prop: {}
      secret1:
        required: true

jobs:
  use-environment:
    environment: ${{ inputs.environment }}
    steps:
      - uses: docker://alpine:3.21
        run: |
          set -x
          [ '${{ vars.env_only_int_prop }}' = '999' ]
          [ "$GLOBALSECRET" = 'secretValue1' ]
          [ '${{ vars.prop1 }}' = 'propValue1' ]

          i=0
          while [ "$i" -le ${#ENVSECRET} ]; do
            echo "${ENVSECRET:$i:1}"
            i=$(( i + 1 ))
          done
        env:
          ENVSECRET: ${{ secrets.env_only_secret_prop }}
          GLOBALSECRET: ${{ secrets.secret1 }}