apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-with-nested-environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  use-environment:
    steps:
      - uses: docker://alpine:3.21
        run: |
          echo "environment: ${{ inputs.environment}}"

  # call-rw-2:
  #   uses: p-gombola/demo-app/.cloudbees/workflows/reusable-with-nested-environment-2.yaml
  #   with:
  #     environment: ${{ inputs.environment }}