apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: scopes

on:
  push:
    branches:
      - "scopes-branch"
    tags:
      - "scopes"

  workflow_dispatch:

env:
  print: 'true'

jobs: 
  scm:
    if: env.print == 'true'
    steps:
      - name: print
        uses: docker://alpine:3.21
        run: |
          echo "cloudbees.scm.ref: ${{ cloudbees.scm.ref }}"
          echo "cloudbees.scm.repositoryUrl: ${{ cloudbees.scm.repositoryUrl }}"
          echo "cloudbees.scm.repository: ${{ cloudbees.scm.repository }}"
          echo "cloudbees.scm.branch: ${{ cloudbees.scm.branch }}"
          echo "print: $print"
