apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: scopes

on:
  workflow_dispatch:

jobs: 
  scm:
    steps:
      - name: print
        uses: docker://alpine:3.21
        run: |
          echo "cloudbees.scm.ref: ${{ cloudbees.scm.ref }}"