apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: skipped-needs
on:
  workflow_dispatch:
jobs:
  job0:
    if: ${{ false }}
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
    outputs:
      out: "1"
  job1:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approve
  approve:
    needs: job0
    if: ${{ false }}
    timeout-minutes: 4320
    delegates: gmaxey/manual-approval/custom-job.yml
    with:
      approvers: ""
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        {}
