apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: skipped-needs
on:
  workflow_dispatch:
jobs:
  job0:
    if: ${{ false }}
    steps:
      - name: Say hello
        id: hello
        run: |
          echo "hello world" > $CLOUDBEES_OUTPUTS/greeting
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
    outputs:
      out: ${{steps.hello.outputs.greeting}}
  job1:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{needs.job0.outputs.out}}"
    needs:
      - job0
  approve:
    needs: job0
    if: ${{ false }}
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml
    with:
      approvers: ""
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        {}
