apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: step-error

on:
  workflow_dispatch:

jobs:
  err:
    steps:
      id: create-error
      uses: docker://invalid.image:latest
      run: |
        echo "pull error"