apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-app-workflow

on:
  workflow_dispatch:

jobs: 
  deploy:
    uses: p-gombola/shared/.cloudbees/workflows/deploy.yaml@main
    with:
      config-path: ./config/demo-app
    secrets:
      access-token: ${{ secrets.token }}
  
  pass:
    needs: [deploy]
    if: needs.deploy.outputs.deploy-result == 'pass'
    steps:
      - name: Pass
        uses: docker://alpine:3.21
        run: echo "Deploy success alert"

  fail:
    needs: [deploy]
    if: needs.deploy.outputs.deploy-result == 'fail'
    steps:
      - name: Handle deploy failure
        uses: docker://alpine:3.21
        run: echo "Deploy failure alert"