apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-app-workflow

on:
  workflow_dispatch:

jobs: 
  deploy:
    environment: secret-env
    uses: p-gombola/shared/.cloudbees/workflows/deploy.yaml@env-secret-bug-2
    secrets:
      top_secret: ${{ secrets.fromEnv }}