apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-app-workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "building..."
          echo "${{secrets.blah_should_not_exist}}"
  
  deploy:
    needs: [build]
    with:
      username: elroy
    secrets:
      deploy_pwd: ${{secrets.superSecretPassword}}
    uses: p-gombola/shared/.cloudbees/workflows/deploy.yaml@main
  
