apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-app-workflow

on:
  workflow_dispatch:

jobs: 
  deploy:
    uses: p-gombola/shared/.cloudbees/workflows/deploy.yaml@main
    with:
      config-path: ./config/demo-app
    secrets:
      access-token: ${{ secrets.token }}