apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-app-workflow

on:
  workflow_dispatch:

jobs: 
  deploy:
    environment: requires-approval
    uses: p-gombola/shared/.cloudbees/workflows/deploy.yaml@environment