name: Reusable Workflow

on:
  workflow_call:

jobs:
  run-script:
    env:
      RW_JOB_ENV: "ENV1"
    runs-on: ubuntu-latest
    steps:
      - name: Print env var
        run: |
          echo "Env var: ${{ env.RW_JOB_ENV }}"